name: shimmer_effect_package_by_ziyodulla
description: A simple Flutter package for adding a shimmer loading effect to any widget.
version: 0.0.1
repository: https://github.com/yourusername/shimmer_container  # Replace with your actual repo
homepage: https://github.com/yourusername/shimmer_container
issue_tracker: https://github.com/yourusername/shimmer_container/issues
author: Devu't <tursunboyevziyodulla30@gmail.com>  # Replace with your email
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/  

topics:
  - shimmer
  - loading
  - animation
