name: shimmer_container
description: A simple Flutter package for adding a shimmer loading effect to any widget.
version: 1.0.0
repository: https://github.com/Ziyodullaxoja17/shimmer_effect_package_by_ziyodulla  # Replace with your actual repo
homepage: https://github.com/Ziyodullaxoja17/shimmer_effect_package_by_ziyodulla
issue_tracker: https://github.com/Ziyodullaxoja17/shimmer_effect_by_ziyodulla/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    # - assets/  # If you plan to add images or sample assets

topics:
  - shimmer
  - loading
  - animation
